### PR TITLE
Add method for directly setting a value

### PR DESCRIPTION
**Pull request by delehef**
It was by far the easiest to manually set the value in my current use case. I open this PR in the case you wish to integrate this feature in the lib.

### CODE REVIEW

**Comment by a8m** [comment]
Good idea.
I'd like to merge this PR, but it looks like you added another commit that not relevant.
Can you fix that @delehef ?

**Comment by delehef** [comment]
You're right, my bad. I opened a new PR with ony the relevant commit.

By the way, would you be interested in a PR for the other change, i.e. displaying the bar when output is a tty and println!-ing the percentage when it's not a tty?

I didn't open a PR because it was a specific case and the implementation is kind of crude.

**Comment by a8m** [comment]
You can pass your own `Writer`, and then handle this logic within the `write` method.

**Comment by delehef** [comment]
Thanks

**Pull request closed without merging**
