### PR TITLE
Implement multiple bar support

### LINKED ISSUE #10: support multiple progress bars

### PR DESCRIPTION
**Pull request by nabijaczleweli**
[Demonstration](https://asciinema.org/a/83456)

Closes #10

### CODE REVIEW

**Comment by nabijaczleweli** [comment]
Anything holding this back?

**Comment by nabijaczleweli** [comment]
Anything holding this back?

**Comment by a8m** [comment]
Hey @nabijaczleweli, sorry for the delay, forgot about this PR.
I'm planning to review this functionality in the next few days and hope we can merge it soon.

Thanks.

**Comment by nabijaczleweli** [comment]
Cool :)

**Comment by nabijaczleweli** [comment]
Cool :)

**Comment by a8m** [comment]
Hey @nabijaczleweli 
I'm trying to run some example using this feature, but it seems like the progress bar loses the synchronization between the bars when adding parallelism to the code. 

Right now I'm in Rome, so I'll investigate it when I'll come back(it will be on Tuesday).

The example:
```rust
fn main() {
    let mut pb0 = ProgressBar::new_level(1000, 0);
    let mut pb1 = ProgressBar::new_level(2000, 1);

    let child0 = thread::spawn(move || {
        for _ in 0..1000 {
            pb0.inc();
            thread::sleep(Duration::from_millis(11));
        }
    });

    let child1 = thread::spawn(move || {
        for _ in 0..2000 {
            pb1.inc();
            thread::sleep(Duration::from_millis(13));
        }
    });

    let _ = child0.join();
    let _ = child1.join();
}
```

Thanks.

**Comment by nabijaczleweli** [comment]
Well, we're doing some rather shady shit with *shared state* in *multiple threads*, which the Rust typesystem will stop you from doing (w/o explicit locking via `Mutex` or `RwLock`)...
Except for the `std*()` streams which are speszol snowfleks (each writer is a separate instance, so there's no way of tracking that).

Try explicitly locking before `draw()`ing and it should work.

This deffo warrants a notice in the docs, thanks for pointing it out.

**Comment by nabijaczleweli** [comment]
Okay, another thing it might be is that writing the PB is done in one write call (internally synchronised) but going back up is another one; I can mitigate that (non-Windooze only, but eh)

**Comment by nabijaczleweli** [comment]
@a8m I fixed the desync issue, but only for non-Windows, see `examples/multi-parallel.rs` doc for why.

**Comment by nabijaczleweli** [comment]
This could use a squashing so please notify me before merging

**Comment by nabijaczleweli** [comment]
Rebased

**Comment by nabijaczleweli** [comment]
Rebased

**Comment by a8m** [comment]
Hi, huge thanks @nabijaczleweli for putting your efforts in making this PR.
I understand that this PR is finished and it looks pretty impressive.
I want to suggest a different api/design for this feature; IMO it can improve it and will make it supported on Windows too.
I’d like to hear your opinion about it, and if you find it as a good approach I can create a PR to your branch and migrate these changes.
The Idea/API comes from [multibar](https://github.com/sethgrid/multibar)

```rust
// create new pool that holds all the progress bars, including there state.
let mut mp = ProgressBar::new_multi_bar();
// multi_bar also has max refresh rate option
mp.set_max_refresh_rate(Some(Duration::from_millis(100)));
mp.println("add an header to your application");
// create_bar creates a progress bar by passing the count and the level
// the multi_bar stores the index(level) of the bar in some data structure somehow
// and pass it a Writer object that forward the output string instead of writing to stdout.
let mut p1 = mp.create_bar(count, level);
mp.println("you can separate bars with blocks of text");
let mut p2 = mp.create_bar(count, level2);
let mut p3 = mp.create_bar(count, leve3);
// start listen to all bars changes
mp.listen();
//
// handle your bars here
//
mp.finish_print("all bars complete");
```

**Comment by nabijaczleweli** [comment]
IMHO that's out of scope/inconsistent with the library in its entirety as it is right now.
Maybe after a major refactor, yes, but not in the current state.

**Comment by nabijaczleweli** [comment]
.

**Comment by nabijaczleweli** [comment]
Any updates on this?

**Comment by a8m** [comment]
Hi @nabijaczleweli ,
Thanks for your contribution to this project. I really appreciate it!

As I suggested before, I prefer the public API a bit different, and __in my opinion__ my suggestion above make the API simpler to the end user (doesn’t need to deal with locks etc..), and also supports another feature, the text lines separators. and I want this feature to be supported.
For this reason, I think it would be better for us to discuss about the API design before starting the implementation in the future.

I created a [PR](https://github.com/a8m/pb/pull/32), and I would like to get a feedback from you.
In the PR I created, there are no changes in the `"pb"` module, and a new module named `"multi"` has been added. 
However, this PR is not finished yet, and it is waiting for your help.
In this PR, you added the "cursor_up" implementation for both unix and windows.
I didn’t want to copy/paste those changes, and I prefer you will add them, since you already did it.

I hope you will understand my point of view, and I appreciate your help.
Thanks.

**Comment by nabijaczleweli** [comment]
> I didn’t want to copy/paste those changes

Why not?

**Comment by a8m** [comment]
I believe you put your effort on it, so the credit belongs to you.

**Comment by nabijaczleweli** [comment]
meh w/e

**Pull request closed without merging**
