### PR TITLE
Fix Redox compilation

### PR DESCRIPTION
**Pull request by jackpot51**
Redox now compiles with cfg(unix) and fully supports the functions used there. One test was disabled on Redox due to stty not being installed by default.

### CODE REVIEW

**Comment by jackpot51** [comment]
@a8m is there anything else you need for this?

**Comment by a8m** [comment]
Thanks for adding this @jackpot51. I missed this PR somehow.

**Comment by jackpot51** [comment]
Thanks for merging! Can a new release be made for crates.io?

**Comment by a8m** [comment]
Done. Thanks!

**Comment by jackpot51** [comment]
Cool!

**Pull request merged**
